spring:
  application:
    name: habit-tracker

  datasource:
    url: jdbc:postgresql://ep-rough-rain-a197dj9t-pooler.ap-southeast-1.aws.neon.tech/neondb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_7gONCxG5WVQb
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${PORT:8080}   # Render will inject PORT, fallback to 8080 locally
  address: 0.0.0.0      # allow external traffic

management:
  endpoints:
    web:
      exposure:
        include: health,info